### ISSUE TITLE
airlab on front

### ISSUE THREAD

**Issue by fruehling76** [beyond-all-reason/BARbarIAn#2]
air-ai started in fron spot (DSDR) while all the other ais staretd in the back of him. later on, the t2 airlab was build on the frontline. multiplayer games airplayer should be always in the back and airlabs in general should be build far away from frontline in a secure place.

**Comment by rlcevg** [comment]
Current AI's start position selection algo:
1) Get cluster of mexes closer to the map center that was not claimed yet by other AI.
2) Select factory that is possible to build on terrain type of selected position, according to importance from factory's config.

Changes required to first pick up strategy/factory to build and then position (may result in no available position), needs more thinking.

t2 labs on front-line was a bug in config, should be fixed in BARb 0.5

**Comment by fruehling76** [comment]
generally starting more in front if map supports that is not wrong as a player that starts with ground army. enough metal spots should be in range though.

but if an ai starts with air it must be go as far as possible back. aircrafts are fast so distance to frontline is not important. on the other side it is weak when getting attacked by enemy ground forces.

i also have the feeling it always start with one airplayer if there are 3 or more players in one team (but i could be wrong here). anyway that should not be like this. better to make also here a random like (60%) of games instead a fix rule.

**Comment by rlcevg** [comment]
Air factory obeys importance rule, but the actual score of factory to select is:
`offset + importance * (mapPercent + speedPercent)`
`importance` is factory's config value;
`offset` is just small +-random number (configurable);
`speedPercent` is value based on average speed of all units in factory;
`mapPercent` for air units is config value (to avoid it being 100%), but it's config constant for all maps;

Because of high speedPercent air factories have the largest score for selection. `no_air` config param exists to forbid 1st N=no_air choices from being air factories.

By tweaking `importance`, air's mapPercent (land's mapPercent is calculated) and `no_air` it is possible to make AI not picking always air as 3rd player's factory. (requires printing of calculated end values, not available without code changes).
